### ISSUE TITLE
Please consider adding an alias "shellcheck" for the "check" job

### ISSUE THREAD

**Issue by julienw** [CircleCI-Public/shellcheck-orb#29]
## Describe Request:
The way to use the orb as a job is to specify `- shellcheck/check:`

As a result, in github we get this output:
![image](https://user-images.githubusercontent.com/454175/97012544-3bcc3780-1548-11eb-81b4-06ce9014d29a.png)

The name `check` isn't very descriptive in a project with a lot of other checks.

Of course we can workaround by making our own job, but this is more work than what could be needed.

Thanks!

**Comment by gmemstr** [comment]
@julienw Thanks for the heads up! For any orb, you can pass along a `name` parameter to a job to override the name, like so:

```yaml
version: 2.1

orbs:
  n: circleci/node@volatile

workflows:
  test:
    jobs:
      - n/test:
          name: "NODEJS TESTS"
```
