### ISSUE TITLE
Expose resource_class for executor on all jobs

### ISSUE THREAD

**Issue by karlmoor-cisco** [CircleCI-Public/shellcheck-orb#56]
## Describe Request:

Currently jobs don't expose a resource_class to use, this means they use the default. Currently this is Large, which is significantly more expensive than Small which would probably be sufficient. If we can expose this santza on the jobs, we can switch to these smaller instances and make our build cheaper.

## Examples:

```
parameters:
  resource_class:
    type: enum
    enum:
      - small
      - medium
      - medium+
      - large
      - xlarge
      - 2xlarge
      - 2xlarge+
    description: Configure the executor resource class
    default: small
```

## Supporting Documentation Links:

An example of when this is exposed can be seen here:
https://circleci.com/developer/orbs/orb/circleci/orb-tools#jobs-pack
