### ISSUE TITLE
Create an executor parameter to allow for custom executors

### ISSUE THREAD

**Issue by jenny-miggin** [CircleCI-Public/shellcheck-orb#58]
## Describe Request:
A static executor is currently defined in the `check` job, but this does not allow for any executor customisations. Allow for a custom executor to be used in place of this, if required

## Examples:
Sample future config: 

```yml
version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.1.3

executors:
  my-small-executor:
    docker:
      - image: cimg/base:stable
    resource_class: small

workflows:
  my_workflow:
    jobs:
      - shellcheck/check:
          dir: ./myScripts
          exclude: SC2148
          executor: my-small-executor
```

## Supporting Documentation Links:
n/a
