### ISSUE TITLE
Allow to set the version of shellcheck when using the `check` job

### ISSUE THREAD

**Issue by timobrembeck** [CircleCI-Public/shellcheck-orb#63]
## Describe Request:

At the moment, the `check` job just runs the version of shellcheck which is included in the CircleCI base image (which corresponds to the Ubuntu repository) and might quite outdated.
Even when the default version of the `install` command is updated (#61/#62), the `check` job would not benefit from this, since `install` is not called here.

## Examples:
```
version: '2.1'
orbs:
  shellcheck: circleci/shellcheck@3.2.0
workflows:
  my_workflow:
    jobs:
      - shellcheck/check:
          dir: ./myScripts
          version: 0.9.0
```
