### ISSUE TITLE
Executor is missing git

### ISSUE THREAD

**Issue by cfra** [CircleCI-Public/shellcheck-orb#9]
I have a CircleCI job like the following:
```
workflows:
  version: 2
  build_ami:
    jobs:
      - shellcheck/check:
          filters:
            tags:
              only:
                - /.*/
```
This works fine for regular builds on branches. However, when I do a build on top of a tag, the following happens:
```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
Enumerating objects: 47, done.
Counting objects: 100% (47/47), done.
Compressing objects: 100% (37/37), done.
Total 5007 (delta 13), reused 23 (delta 7), pack-reused 4960
object not found
```

I think this is not really the best possible behavior.

I am not sure what the best way to address this would be.

One thing I could think of would be the creation of a `circleci/shellckeck` docker image instead of the upstream `koalaman` images, and installing git and ssh into this image.

If someone could point me into the right direction for solving this, I would be willing to work on it.
